[package]
name = "ichigo-lang"
version = "0.1.0"
authors = ["PragmaTwice <i@twice.moe>"]
edition = "2018"

[dependencies]
pest = "2.1.2"
pest_derive = "2.1.0"
colored = "1.9.1"
structopt = "0.3.7"
maplit = "1.0.2"
lazy_static = "1.4.0"
regex = "1.5.5"
