[package]
name = "ichigo-lang"
version = "0.1.0"
authors = ["PragmaTwice <i@twice.moe>"]
edition = "2018"

[dependencies]
pest = "2.1.1"
pest_derive = "2.1.0"
colored = "1.8"
clap = {version = "~2.27.0", features = ["yaml"]}
maplit = "1.0.2"
lazy_static = "1.4.0"
regex = "1.3.1"
